api_platform:
    title: '%env(API_PLATFORM_TITLE)%'
    version: '%env(API_PLATFORM_VERSION)%'
    description: '%env(API_PLATFORM_DESCRIPTION)%'
    formats:
        jsonld:
            mime_types:
                - application/ld+json
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html
    patch_formats:
        json:
            mime_types:
                - application/merge-patch+json
    error_formats:
        jsonproblem:
            mime_types:
                - application/problem+json
        jsonld:
            mime_types:
                - application/ld+json
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    collection:
        pagination:
            enabled: true
            items_per_page_parameter_name: itemsPerPage
            page_parameter_name: page

